baseURL = "https://jadi.space/"
locale = "en-US"
title = "Jadi"
theme = "archie"
copyright = "© Jadi Mirmirani"

enableRobotsTXT = true

[params]
  mode = "auto"      # light / dark / auto / toggle
  useCDN = false
  description = "Essential info about Jadi Mirmirani: contact, links and ways to support."
  mainSections = []

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 2
[[menu.main]]
  name = "Links"
  url = "/links/"
  weight = 3
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4
[[menu.main]]
  name = "Support"
  url = "/support/"
  weight = 5

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
